dependencies:
  - 'vendor/**/*'
documentation:
  - '**/*.md'
  - 'examples/**/*'
  - 'website/**/*'
provider:
  - '.github/**/*'
  - '.gitignore'
  - '.go-version'
  - '*.md'
  - 'docs/**/*'
  - 'GNUmakefile'
  - 'main.go'
  - 'vsphere/**/*'
  - 'website/docs/index.html.markdown'
