---
version: "2"

output:
  formats:
    text:
      path: stdout

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    errcheck:
      exclude-functions:
        - github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set
        - fmt:.*
        - io:Close
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # TODO: Setting temporary exclusions for specific linters.
      - linters:
          - gosec
        text: G107
      - linters:
          - gosec
        text: G109
      - linters:
          - gosec
        text: G115
      - linters:
          - gosec
        text: G401
      - linters:
          - gosec
        text: G402
      - linters:
          - gosec
        text: G505
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - revive
        text: var-naming
      - linters:
          - staticcheck
        text: SA1019
      - linters:
          - unused
        text: is unused
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
