---
version: "2"

output:
  formats:
    text:
      path: stdout

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Exclude specific rules to suppress false positives or acceptable issues.
      - linters:
          - gosec
        text: G115|G401
      - linters:
          - staticcheck
        text: SA1019
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
