---
blank_issues_enabled: false
contact_links:
  - name: Community Discussions
    url: https://github.com/vmware/terraform-provider-vsphere/discussions
    about: Need some help? Join the community discussions.
  - name: Terraform Provider Documentation
    url: https://registry.terraform.io/providers/vmware/vsphere/latest/docs
    about: Having trouble with this Terraform provider? Check out the provider documentation.
  - name: Terraform Documentation
    url: https://developer.hashicorp.com/terraform/docs
    about: Having trouble with Terraform? Check out the product documentation.
