# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: "Enhancement Request"
description: Is something critical missing? Suggest an enhancement or feature.
title: "Add support for [REPLACE WITH SHORT DESCRIPTION]"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Before filing an enhancement or feature, please [search the existing issues](https://github.com/hashicorp/terraform-provider-vsphere/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement) for related requests, and use the [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) feature to add up-votes to existing requests.
        
        When filing an enhancement issue, please include the following information.
  - type: checkboxes
    id: terms
    attributes:
      label: Community Guidelines
      description: The HashiCorp Community Guidelines apply to you when interacting with the community here on GitHub and contributing code.
      options:
        - label: I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
          required: true
        - label: Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
          required: false
        - label: Do not leave "+1" or other comments that do not add relevant information or questions.
          required: false
        - label: If you are interested in working on this issue or have submitted a pull request, please leave a comment.
          required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A written overview of the enhancement or feature.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case(s)
      description: Please provide a use case or scenario.
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: Potential Terraform Provider Configuration
      description: |
        Provide a potential Terraform provider configuration.
        Learn more about [Code Formatting](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).
      placeholder: |
        Please format any code in code blocks using the markdown editor.
    validations:
      required: false
  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Please provide any related GitHub issues or pull requests (open or closed) or documentation.
        Learn about [Referencing Github Issues](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests).
      placeholder: |
        #GH-0000
    validations:
      required: false
