export TF_VAR_VSPHERE_NAS_HOST=${nas_host}
export TF_VAR_VSPHERE_ESXI1=${esxi_host_1}
export TF_VAR_VSPHERE_ESXI1_PW='${esxi_host_1_pw}'
export VSPHERE_SERVER=${vsphere_host}
export TF_VAR_VSPHERE_PRIVATE_NETWORK='${private_network}'

export VSPHERE_USER="administrator@vcenter.test.local"
export VSPHERE_PASSWORD="Password123!"
export VSPHERE_ALLOW_UNVERIFIED_SSL=true

export TF_VAR_VSPHERE_SERVER=$VSPHERE_SERVER
export TF_VAR_VSPHERE_USER=$VSPHERE_USER
export TF_VAR_VSPHERE_PASSWORD=$VSPHERE_PASSWORD
export TF_VAR_VSPHERE_ALLOW_UNVERIFIED_SSL=$VSPHERE_ALLOW_UNVERIFIED_SSL
