name: Nightly Acceptance tests

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 12:00 AM UTC

jobs:
  acceptance_tests:
    runs-on: ubuntu-latest
    environment: acctests
    env:
      TF_VAR_VSPHERE_ESXI1: ${{ secrets.TF_VAR_VSPHERE_ESXI1 }}
      TF_VAR_VSPHERE_ESXI1_PW: ${{ secrets.TF_VAR_VSPHERE_ESXI1_PW }}
      TF_VAR_VSPHERE_LICENSE: ${{ secrets.TF_VAR_VSPHERE_LICENSE }}
      TF_VAR_VSPHERE_PRIVATE_NETWORK: ${{ secrets.TF_VAR_VSPHERE_PRIVATE_NETWORK }}
      TF_VAR_VSPHERE_PUBLIC_NETWORK: ${{ secrets.TF_VAR_VSPHERE_PUBLIC_NETWORK }}
      VSPHERE_PASSWORD: ${{ secrets.VSPHERE_PASSWORD }}
      VSPHERE_SERVER: ${{ secrets.VSPHERE_SERVER }}
      VSPHERE_USER: ${{ secrets.VSPHERE_USER }}
      TF_VAR_VSPHERE_CLUSTER: ${{ vars.TF_VAR_VSPHERE_CLUSTER }}
      TF_VAR_VSPHERE_DATACENTER: ${{ vars.TF_VAR_VSPHERE_DATACENTER }}
      TF_VAR_VSPHERE_ESXI1_BOOT_DISK1: ${{ vars.TF_VAR_VSPHERE_ESXI1_BOOT_DISK1 }}
      TF_VAR_VSPHERE_ESXI1_BOOT_DISK1_SIZE: ${{ vars.TF_VAR_VSPHERE_ESXI1_BOOT_DISK1_SIZE }}
      TF_VAR_VSPHERE_ESXI_TRUNK_NIC: ${{ vars.TF_VAR_VSPHERE_ESXI_TRUNK_NIC }}
      TF_VAR_VSPHERE_PG_NAME: ${{ vars.TF_VAR_VSPHERE_PG_NAME }}
      VSPHERE_ALLOW_UNVERIFIED_SSL: ${{ vars.VSPHERE_ALLOW_UNVERIFIED_SSL }}
      VSPHERE_PERSIST_SESSION: true
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ref: 'main'
  
      - name: Write the SSH key and create session folders
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./ssh_private_key
          chmod 600 ./ssh_private_key
          echo "TF_VAR_PRIV_KEY=$(pwd)/ssh_private_key" >> $GITHUB_ENV
          mkdir -p sessions
          echo "VSPHERE_VIM_SESSION_PATH=$(pwd)/sessions" >> $GITHUB_ENV
          mkdir -p rest_sessions
          echo "VSPHERE_REST_SESSION_PATH=$(pwd)/rest_sessions" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_wrapper: false

      - name: Create testrun resources
        run: |
          cd acctests/vsphere/testrun
          terraform init
          terraform apply -auto-approve
          while read -r line; do
            if [[ $line == export* ]]; then
              echo "${line#export }" >> $GITHUB_ENV
            fi
          done < devrc

      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: '.go-version'
      
      - name: Set up Node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # 3.8.1
        with:
          node-version: 18

      # Due to third party action restrictions, install and use the tool directly
      - name: Set up gotestfmt
        run: go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

      - name: Go mod verify
        run: go mod verify
      
      - name: Run acceptance tests
        continue-on-error: true
        run: |
          set -euo pipefail
          TF_ACC=1 go test -json -v ./... -timeout 360m 2>&1 | tee /tmp/gotest.log | gotestfmt
      
      - name: Get today's date
        run: echo "TODAY_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Upload test log
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: test-log-${{ env.TODAY_DATE }}
          path: /tmp/gotest.log

      - name: Panic check
        run: |
          if grep -q "panic:" /tmp/gotest.log; then
            echo "Panic found in log file."
            exit 1
          else
            echo "No panic found in log file."
          fi

      - name: Summary
        run: node ./scripts/summarize-testlog.js /tmp/gotest.log

      - name: Get yesterday's date
        run: echo "YESTERDAY_DATE=$(date -d 'yesterday' +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Download previous day's log file
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615 # v2.27.0
        with:
          name: test-log-${{ env.YESTERDAY_DATE }}
          workflow_conclusion: "" # ignore status
          search_artifacts: true
          path: /tmp/yesterday

      - name: Regression check
        run: node ./scripts/compare-testlogs.js /tmp/gotest.log /tmp/yesterday/gotest.log

      - name: Cleanup testrun resources
        if: always()
        run: |
          cd acctests/vsphere/testrun
          terraform destroy -auto-approve
