name: Automate labeled issues
on:
  issues:
    types: [labeled]
jobs:
  Move_Blocked_Issue_On_Working_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: aareet/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.vsphere_github_actions }}"
        project-url: "https://github.com/orgs/hashicorp/projects/60"
        column-name: "Blocked"
        label-name: "waiting-response"
  Move_Crash_Issue_On_Working_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: aareet/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.vsphere_github_actions }}"
        project-url: "https://github.com/orgs/hashicorp/projects/60"
        column-name: "To do"
        label-name: "crash"
