---
name: Check Documentation

on:
  pull_request:

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Install Tools
      run: make tools
    - name: Check Structure
      run: make docs-check
    - name: Check HCL Formatting
      run: make docs-hcl-lint
