---
name: golangci-lint

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - '/*'
      - '!main.go'
      - 'acctests/**'
      - 'docs/**'
      - README.md
      - 'scripts/**'
  push:
    paths-ignore:
      - '.github/**'
      - '/*'
      - '!main.go'
      - 'acctests/**'
      - 'docs/**'
      - README.md
      - 'scripts/**'
  schedule:
    - cron: 30 00 * * 1

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: go.mod
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run Linters
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: latest
