name: Issue Comment Created Triage

on:
  issue_comment:
    types: [created]

jobs:
  issue_comment_triage:
    runs-on: ubuntu-latest
    steps:
      - id: remove-stale
        uses: ./.github/workflows/remove-issue-label.yml
        with:
          label-name: "stale"
      - id: remove-waiting-response
        uses: ./.github/workflows/remove-issue-label.yml
        with:
          label-name: "waiting-response"