name: Issue Comment Created Triage

on:
  issue_comment:
    types: [created]

jobs:
  issue_comment_triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: stale
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: waiting-response