name: Issue Comment Created Triage

on:
  issue_comment:
    types: [created]

jobs:
  remove-foobar:
    uses: ./.github/workflows/remove-issue-label.yml
    with:
      label-name: "waiting-response"
  remove-stale:
    uses: ./.github/workflows/remove-issue-label.yml
    with:
      label-name: "stale"
