name: Issue Opened Triage

on:
  issues:
    types: [opened]

jobs:
  issue_triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: github/issue-labeler@v2.6
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler-issue-triage.yml
        enable-versioned-regex: 0