name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  go-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.go-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - id: go-version
        run: echo "::set-output name=version::$(cat ./.go-version)"
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Release Notes
        run: sed -n -e "1{/# /d;}" -e "2{/^$/d;}" -e "/# $(git describe --abbrev=0 --exclude="$(git describe --abbrev=0 --match='v*.*.*' --tags)" --match='v*.*.*' --tags | tr -d v)/q;p" CHANGELOG.md > release-notes.txt
      - uses: actions/upload-artifact@v2
        with:
          name: release-notes
          path: release-notes.txt
          retention-days: 1

      - name: Setup hc-releases
        uses: hashicorp/actions-setup-hc-releases@v2
        with:
          github-token: ${{ secrets.CODESIGN_GITHUB_TOKEN }}
        
        terraform-provider-release:
          name: 'Terraform Provider Release'
          needs: [go-version, release-notes]
          uses: hashicorp/ghaction-terraform-provider-release/.github/workflows/hashicorp.yml@v1
          secrets:
            hc-releases-github-token: '${{ secrets.HASHI_RELEASES_GITHUB_TOKEN }}'
            hc-releases-terraform-registry-sync-token: '${{ secrets.TF_PROVIDER_RELEASE_TERRAFORM_REGISTRY_SYNC_TOKEN }}'
            setup-signore-github-token: '${{ secrets.HASHI_SIGNORE_GITHUB_TOKEN }}'
            signore-client-id: '${{ secrets.SIGNORE_CLIENT_ID }}'
            signore-client-secret: '${{ secrets.SIGNORE_CLIENT_SECRET }}'
          with:
            release-notes: true
            setup-go-version: '${{ needs.go-version.outputs.version }}'
          env:
            HC_RELEASES_HOST_STAGING: '${{ secrets.HC_RELEASES_HOST_STAGING }}'
            HC_RELEASES_KEY_STAGING: '${{ secrets.HC_RELEASES_KEY_STAGING }}'

      - name: Create Release metadata
        uses: hashicorp/actions-hc-releases-create-metadata@v1
        with:
          private-tools-token: ${{ secrets.CODESIGN_GITHUB_TOKEN }}
          product-name: "terraform-provider-vsphere"
          version: ${{ github.ref_name }}
          hc-releases-host: ${{ secrets.HC_RELEASES_HOST_STAGING}}
          hc-releases-key: ${{ secrets.HC_RELEASES_KEY_STAGING }}
     
      - name: Promote
        uses: hashicorp/actions-hc-releases-promote@v1
        with:
          product-name: "terraform-provider-vsphere"
          version: ${{ github.ref_name }}
          hc-releases-host: ${{ secrets.HC_RELEASES_HOST_PROD }}
          hc-releases-key: ${{ secrets.HC_RELEASES_KEY_PROD }}
          hc-releases-source_env_key: ${{ secrets.HC_RELEASES_KEY_STAGING }}
      