name: Remove specified label from issue

on:
  # This file is reused, and called from other workflows
  workflow_call:
      inputs:
        label-name:
          required: true
          type: string


jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@e69ef5462fd455e02edcaf4dd7708eda96b9eda0 # v7.0.0
        env:
          REMOVE_LABEL: ${{ inputs.label-name }}
        with:
          script: |
            const { REMOVE_LABEL } = process.env
            console.log(`Attempting to remove label "${REMOVE_LABEL}"`)
            
            const { data } = await github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            
            // Return early if there are no labels
            if (data.length == 0){
              console.log(`Issue has no labels; not attempting to remove label "${REMOVE_LABEL}"`)
              return
            }
            
            // Check if REMOVE_LABEL is present
            const filteredData = data.filter(label => label.name == REMOVE_LABEL)
            
            // Return early if filtering didn't identify the label as present
            if (filteredData.length == 0){
              console.log(`Label "${REMOVE_LABEL}" not found on issue; not attempting to remove it.`)
              return
            }

            console.log(`Label "${REMOVE_LABEL}" found! Now deleting it from the issue...`)

            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: REMOVE_LABEL
            })